server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: demod-agent-system
  static_configs:
  - targets:
      - localhost
  pipeline_stages:
  - json:
  - regex:
    expression: '^(?P<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d+).*?(?P<level>INFO|WARN|ERROR|DEBUG).*$'
  - timestamp:
    source: time
    format: RFC3339Nano
  - labels:
    level:
    service:
    instance:
  - output:
    source: output

- job_name: demod-agent-system-file
  static_configs:
  - targets:
      - localhost
  file_sd_configs:
  - files:
    - /etc/promtail/file_discovery.yml

limits_config:
  readline_max: 4096

target_config:
  sync_period: 10s

sync:
  max_stale: 10m

ingester:
  client:
    external_labels:
      environment: production
      cluster: demod-main