auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1:7946
    ring_buffer:
      kvstore:
        store: inmemory
        replication_factor: 1
    max_transfer_retries: 0
    final_sleep: 0s
    heartbeat_period: 10s
    observe_period: 1s
    flush_period: 1m
    num_flushers: 4
    flush_check_period: 10s
    chunk_idle_period: 30s
    chunk_retain_period: 30s
    chunk_gc_period: 1m
    chunk_target_size: 1048576
    max_chunk_age: 72h
    concurrent_flushes: 4

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

limits_config:
  enforce_metric_name: false
  max_old_streams: 1000
  max_entries_limit_per_query: 10000
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s
  query_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 72h

query_range:
  split_queries_by_interval: 15m
  max_query_look_back: 0s
  max_query_parallelism: 32

frontend:
  max_outstanding_per_tenant: 2048
  worker:
    grpc_server_max_recv_msg_size: 104857600
    grpc_server_max_send_msg_size: 104857600